List<String> alergias = [
  'Maní',
  'Nueces de árbol',
  'Mariscos',
  'Pescado',
  'Leche',
  'Huevos',
  'Soya',
  'Trigo',
  'Frutas',
  'Legumbres',
  'Polvo',
  'Ácaros del polvo',
  'Polen',
  'Moho',
  'Caspa de animales',
  'Penicilina',
  'AINEs',
  'Medicamentos anticonvulsivos',
  'Vacunas y sueros',
  'Níquel',
  'Látex',
  'Fragancias',
  'Conservantes',
  'Detergentes',
  'Tintes para el cabello',
  'Productos para la piel',
  'Veneno de insectos',
  'Esporas de hongos'
];
List<String> enfermedadesPreexistentes = [
  "Diabetes tipo 1",
  "Diabetes tipo 2",
  "Hipertensión arterial",
  "Asma bronquial",
  "Enfermedad cardíaca congénita",
  "Enfermedad coronaria",
  "Insuficiencia cardíaca",
  "Enfermedad renal crónica",
  "Insuficiencia renal",
  "Glomerulonefritis",
  "Enfermedad pulmonar obstructiva crónica (EPOC)",
  "Fibrosis quística",
  "Enfermedad tiroidea (hipotiroidismo e hipertiroidismo)",
  "Tiroiditis de Hashimoto",
  "Enfermedad de Graves",
  "Artritis reumatoide",
  "Lupus eritematoso sistémico",
  "Esclerodermia",
  "Enfermedad de Crohn",
  "Colitis ulcerosa",
  "Síndrome del intestino irritable (SII)",
  "Epilepsia",
  "Depresión mayor",
  "Trastorno bipolar",
  "Trastornos de ansiedad",
  "Esquizofrenia",
  "Hepatitis B",
  "Hepatitis C",
  "VIH/SIDA",
  "Obesidad mórbida",
  "Anemia falciforme",
  "Talasemia",
  "Enfermedad celiaca",
  "Psoriasis",
  "Vitíligo",
  "Enfermedades autoinmunes múltiples",
  "Enfermedades inflamatorias del intestino",
  "Enfermedades neuromusculares",
  "Cáncer (diversos tipos)",
  "Esclerosis múltiple",
  "Miastenia gravis"
];

List<String> medicamentosDuranteEmbarazo = [
  "Ácido fólico",
  "Hierro (sulfato ferroso, gluconato ferroso)",
  "Vitamina D (colecalciferol)",
  "Calcio (carbonato de calcio, citrato de calcio)",
  "Prenatales multivitamínicos",
  "Insulina (para la diabetes)",
  "Metformina",
  "Levotiroxina (para hipotiroidismo)",
  "Propiltiouracilo (para hipertiroidismo)",
  "Heparina de bajo peso molecular (enoxaparina)",
  "Labetalol (para hipertensión)",
  "Nifedipino (para hipertensión)",
  "Metildopa (para hipertensión)",
  "Corticosteroides (prednisona, dexametasona)",
  "Albuterol (para asma)",
  "Budesonida (para asma)",
  "Antidepresivos selectivos (fluoxetina, sertralina)",
  "Antipsicóticos (olanzapina, quetiapina)",
  "Antiácidos (hidróxido de aluminio, magnesio)",
  "Ranitidina (para reflujo gastroesofágico)",
  "Omeprazol (para reflujo gastroesofágico)",
  "Metoclopramida (para náuseas y vómitos)",
  "Ondansetrón (para náuseas y vómitos)",
  "Paracetamol (acetaminofén para el dolor)",
  "Ibuprofeno (usado con precaución en ciertos trimestres)",
  "Antihistamínicos (loratadina, cetirizina)",
  "Suplementos de omega-3",
  "Progestágenos (progesterona)",
  "Betametasona (para maduración pulmonar fetal)",
  "Magnesio (para la prevención de la preeclampsia)",
  "Doxiciclina (usada con precaución)",
  "Macrólidos (azitromicina, eritromicina)",
  "Penicilinas (amoxicilina, ampicilina)",
  "Cefalosporinas (ceftriaxona, cefalexina)"
];
