// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBMU_eWBnTgCBjCs4qudNJWqULDRDI5M',
    appId: '1:877846277125:web:5508b2c6525759d1f8406c',
    messagingSenderId: '877846277125',
    projectId: 'salud-materna-eda0e',
    authDomain: 'salud-materna-eda0e.firebaseapp.com',
    storageBucket: 'salud-materna-eda0e.firebasestorage.app',
    measurementId: 'G-3MTY68DBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMsHO5XsF2dsYPni7q8hosLRGC3KeJX4Y',
    appId: '1:877846277125:android:40c5e63229db0b1bf8406c',
    messagingSenderId: '877846277125',
    projectId: 'salud-materna-eda0e',
    storageBucket: 'salud-materna-eda0e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCBMU_eWBnTgCBjCs4qudNJWqULDRDI5M',
    appId: '1:877846277125:web:5508b2c6525759d1f8406c',
    messagingSenderId: '877846277125',
    projectId: 'salud-materna-eda0e',
    authDomain: 'salud-materna-eda0e.firebaseapp.com',
    storageBucket: 'salud-materna-eda0e.firebasestorage.app',
    measurementId: 'G-3MTY68DBDR',
  );

}